{{- if eq .Requirements.webhook "prow" }}
enabled: true
{{- else }}
enabled: false
{{- end }}

hmacToken: "{{ .Parameters.prow.hmacToken }}"
oauthToken: "{{ .Parameters.pipelineUser.token }}"
user: "{{ .Parameters.pipelineUser.username }}"

buildnum:
  enabled: false
pipelinerunner:
  args:
  - controller
  - pipelinerunner
  enabled: "true"
tillerNamespace: ""

sinker:
  replicaCount: 0

