cluster:
  domain: {{ .Requirements.ingress.domain }}
  namespace: {{ .Requirements.cluster.namespace | default "jx" }}
  namespaceSubDomain: {{ .Requirements.ingress.namespaceSubDomain | default ".jx." }}
{{- if hasKey .Requirements.cluster "project" }}
  projectID: {{ .Requirements.cluster.project }}
{{- else }}
  projectID: ""
{{- end }}
{{- if hasKey .Requirements.cluster "zone" }}
  zone:  {{ .Requirements.cluster.zone }}
{{- else }}
  zone: ""
{{- end }}
  name: ""
  serverUrl: ""
{{- if .Requirements.ingress.tls.enabled }}
  tls: true
{{- end }}

gitops:
  versionStreamUrl: {{ .Requirements.versionStream.url }}
  versionStreamRef: {{ .Requirements.versionStream.ref }}

  gitKind: {{ .Requirements.cluster.gitKind | default "github" }}
  gitName: {{ .Requirements.cluster.gitName | default "github" }}
  server: {{ .Requirements.cluster.gitServer | default "https://github.com" }}
  owner: {{ .Requirements.cluster.environmentGitOwner }}
  webhook: {{ .Requirements.webhook | default "prow" | title | quote }}
{{- if eq .Requirements.cluster.gitKind "bitbucketserver" }}
  gitUrlPathPrefix: "/scm"
{{- else }}
  gitUrlPathPrefix: ""
{{- end }}

  dev:
    server: ""
{{- if .Requirements.gitops }}
    repo: "{{ .Environments.dev.repository }}"
    owner: "{{ .Environments.dev.owner }}"
    envOrganisation: "{{ .Requirements.cluster.environmentGitOwner }}"
{{- else }}
    repo: ""
    owner: ""
    envOrganisation: ""
{{- end }}
{{- if eq .Requirements.cluster.provider "gke" }}
    dockerRegistryOrg: "{{ .Requirements.cluster.project }}"
{{- else }}
    dockerRegistryOrg: ""
{{- end }}


  staging:
    repo: "{{ .Environments.staging.repository }}"
    owner: "{{ .Environments.staging.owner | default .Requirements.cluster.environmentGitOwner }}"
    server: ""

  production:
    repo: "{{ .Environments.production.repository }}"
    owner: "{{ .Environments.production.owner | default .Requirements.cluster.environmentGitOwner }}"
    server: ""

storage:
  logs:
    url: "{{ .Requirements.storage.logs.url }}"
  reports:
    url: "{{ .Requirements.storage.reports.url }}"
  repository:
    url: "{{ .Requirements.storage.repository.url }}"

expose:
  enabled: false

cleanup:
  enabled: false

controllerbuild:
  enabled: true
controllerteam:
  enabled: false
controllerworkflow:
  enabled: false
jenkins:
  enabled: false
jenkins-x-platform:
  controllerbuild:
    enabled: true
  jenkins:
    Agent:
      PodTemplates:
        Go:
          Containers:
            Go:
              Image: jenkinsxio/builder-go:latest
        Maven:
          Containers:
            Maven:
              Image: jenkinsxio/builder-maven:latest
          volumes:
          - mountPath: /root/.m2/
            secretName: jenkins-maven-settings
            type: Secret
          - mountPath: /home/jenkins/.docker
            secretName: jenkins-docker-cfg
            type: Secret
        Nodejs:
          Containers:
            Nodejs:
              Image: jenkinsxio/builder-nodejs:latest
  monocular:
    api:
      livenessProbe:
        initialDelaySeconds: 1000
  nexus:
    persistence:
      size: 100Gi
  postinstalljob:
    enabled: "true"

tekton:
  webhook:
    enabled: false

JenkinsXGitHub:
  username: "{{ .Parameters.pipelineUser.username }}"
  password: "{{ .Parameters.pipelineUser.token }}"

{{- if .Requirements.ingress.tls }}
certmanager:
  production: "{{ .Requirements.ingress.tls.production }}"
{{- if .Requirements.ingress.tls.enabled }}
  email:  "{{ .Requirements.ingress.tls.email }}"
{{- else }}
  enabled: false
{{- end }}
{{- end }}

sso:
  enabled: true

tekton:
  auth:
    docker:
      username: vault:tekton-weasel/creds/tekton-docker:username
      password: vault:tekton-weasel/creds/tekton-docker:password # pragma: allowlist secret
      url: https://index.docker.io/v1/


JenkinsXBDD: vault:tekton-weasel/sa/jenkins-x-bdd:json

ui:
  skipExposeService: true
  sso:
    create: true
    certIssuerName: letsencrypt-prod
    domain: "{{ .Requirements.ingress.domain }}"
    oidcIssuerUrl: "https://dex-jx.{{ .Requirements.ingress.domain }}"

JenkinsXGHETestUser:
  username: vault:tekton-weasel/creds/jenkins-x-github-ent-test-user:username
  password: vault:tekton-weasel/creds/jenkins-x-github-ent-test-user:password # pragma: allowlist secret

JenkinsXBBSTestUser:
  username: vault:tekton-weasel/creds/jenkins-x-bbs-test-user:username
  password: vault:tekton-weasel/creds/jenkins-x-bbs-test-user:password # pragma: allowlist secret

JenkinsXGitLabTestUser:
  username: vault:tekton-weasel/creds/jenkins-x-gitlab-test-user:username
  password: vault:tekton-weasel/creds/jenkins-x-gitlab-test-user:password # pragma: allowlist secret

TestJenkinsUser:
  username: vault:tekton-weasel/creds/test-jenkins-user:username
  password: vault:tekton-weasel/creds/test-jenkins-user:password # pragma: allowlist secret

JenkinsXGKEServiceAccount:
  filename: vault:tekton-weasel/sa/jenkins-x-sa:filename
  data: vault:tekton-weasel/sa/jenkins-x-sa:data

JenkinsXGitHubTest:
  username: vault:tekton-weasel/creds/gh-test:username
  password: vault:tekton-weasel/creds/gh-test:password # pragma: allowlist secret

GcsJenkinsXChartMuseumKey: vault:tekton-weasel/sa/chartmuseum-gcs:data

arcalos:
  adminUsername: vault:tekton-weasel/arcalos:admin-username
  dashboardAuthId: vault:tekton-weasel/arcalos:dashboard-auth-id
  dashboardAuthSecret: vault:tekton-weasel/arcalos:dashboard-auth-secret # pragma: allowlist secret
  domainIssuerPassword: vault:tekton-weasel/arcalos:domain-issuer-password # pragma: allowlist secret
  domainIssuerUsername: vault:tekton-weasel/arcalos:domain-issuer-username
  pipelineGithubUser: vault:tekton-weasel/arcalos:pipeline-github-user
  pipelineGithubToken: vault:tekton-weasel/arcalos:pipeline-github-token
  gitOwner: jenkins-x-bot-test
  prowHMACToken: vault:tekton-weasel/arcalos:prow-hmac-token
  ciSA: vault:tekton-weasel/arcalos/sa:json